// Generated by CoffeeScript 1.6.3
(function() {
  var cheerio, request;

  request = require('request');

  cheerio = require('cheerio');

  module.exports = {
    depth: function(next) {
      return request('https://www.korbit.co.kr', function(err, res, body) {
        var $, asks, bids, span5;
        if (err) {
          return next(err);
        }
        $ = cheerio.load(body);
        span5 = $('.span5.offset1').next();
        bids = [];
        asks = [];
        $('tr', span5).slice(2).each(function(i, elem) {
          var ask_a, ask_b, bid_a, bid_b, _ref;
          _ref = $('td', this).map(function() {
            return $(this).text();
          }), bid_b = _ref[0], bid_a = _ref[1], ask_a = _ref[2], ask_b = _ref[3];
          bids.push([bid_a, bid_b]);
          return asks.push([ask_a, ask_b]);
        });
        return next(null, {
          bids: bids,
          asks: asks
        });
      });
    }
  };

}).call(this);
